name: CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: GitHub Authorization
        run: |
          git config remote.origin.url https://wirbot:$token@github.com/lzrby/squash
        env:
          token: ${{ secrets.GH_TOKEN }}
      - name: Run gh-pages deploy
        run: |
          cd leaderboard-ui
          npm i
          npm run deploy -- -u "wirbot <wir.development@gmail.com>"
      - name: Update Deployment Status
        run: |
          cd leaderboard-ui
          npm run gds -- --token $token -a create -e github-pages -r $sha
          npm run gds -- --token $token -a success -e github-pages -r $sha -l https://lzrby.github.io/squash
        env:
          sha: ${{ github.sha }}
          token: ${{ secrets.GH_TOKEN }}
